/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unleash.sdk.example;
import io.getunleash.*;
import io.getunleash.util.*;
import java.lang.Thread;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        UnleashConfig config = UnleashConfig.builder()
        .appName("unleash-sdk-example-java")
        .instanceId("your-instance-1")
        .sendMetricsInterval(1)
        .unleashAPI("http://localhost:4242/api/")
        .apiKey("apiKey")
        .synchronousFetchOnInitialisation(true)
        .build();

        Unleash unleash = new DefaultUnleash(config);
        if (unleash.isEnabled("test-flag")) {
            System.out.println("Flag is enabled");
        } else {
            System.out.println("Flag is disabled");
        }
        try {
            // lets send some metrics! :D ;D !!! xD
            Thread.sleep(5000);
        }
        catch(InterruptedException ex) {
            System.out.println("Interrupted");
            Thread.currentThread().interrupt();
        }
    }
}
