trustPolicy: no-downgrade

# The minimum age of a release to be considered for dependency installation.
# The value is in minutes (1440 minutes = 1 day).
# 2880 minutes = 2 days
minimumReleaseAge: 2880
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - "unleash-client"
