allowBuilds:
  esbuild: true

trustPolicy: no-downgrade

# The minimum age of a release to be considered for dependency installation.
# The value is in minutes (1440 minutes = 1 day).
# 10 080 minutes = 7 days
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - "@unleash/proxy-client-vue"
  - "unleash-proxy-client"
  - "prettier"
